### ISSUE TITLE
Install extras and ZSH

### ISSUE THREAD

**Issue by davebulaval** [life4/textdistance#37]
Since ZSH shell use bracket (`[ ]`) as a globbing/regex pattern detection the command `pip install textdistance[extras]` won't work. 

The work around is to use escape character as explain in this [Stack solution](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity).

Solution:
`pip install 'textdiantce[extras]'`

**Comment by orsinium** [comment]
Thank you! Do you want to make PR?

**Comment by davebulaval** [comment]
@orsinium done #38

**Comment by davebulaval** [comment]
Awesome work btw.

**Comment by orsinium** [comment]
The best practice is to keep the issue open while PR isn't accepted. You can write `close #37` in the description of the PR, and when PR merged, the issue will be closed automatically.

**Comment by davebulaval** [comment]
didn't know that. tks
