### ISSUE TITLE
JaroWinkler-similarity gives different results when using textdistance vs textdistance[extras]

### ISSUE THREAD

**Issue by Rijgersberg** [life4/textdistance#39]
I've discovered an inconsistency in computed Jaro-Winkler similarities between using `textdistance` and `textdistance[extras]`, and I think it is a bug.

Minimal example:

```bash
$ mkvirtualenv --python=python3.7 textdistance-plain
$ pip install textdistance
$ python -c "from textdistance import JaroWinkler; print(JaroWinkler().similarity('duck donald', 'duck daisy'))"
0.8672727272727273
```
vs

```bash
$ mkvirtualenv --python=python3.7 textdistance-extras
$ pip install textdistance[extras]
$ python -c "from textdistance import JaroWinkler; print(JaroWinkler().similarity('duck donald', 'duck daisy'))"
0.9115151515151515
```
I'm using python 3.7.4 and textdistance 4.1.4.

**Comment by bartbroere** [comment]
This becomes a game of "Spot the differences" :-)

[The implementation of this repository (textdistance without extras)](https://github.com/life4/textdistance/blob/33b67ae0d5286560a16fe3d9388a43016cdf3fc4/textdistance/algorithms/edit_based.py#L221-L319)

[The implementation of jellyfish](https://github.com/jamesturk/jellyfish/blob/713a432f0435ee2060923694df7904d0371f2c4a/jellyfish/_jellyfish.py#L43-L110)

[The implementation of python-Levenshtein](https://github.com/ztane/python-Levenshtein/blob/811c050ab71593879804a61347352764837d000f/Levenshtein/_levenshtein.c#L2811-L2843)

**Comment by Rijgersberg** [comment]
> This becomes a game of "Spot the differences" :-)
> 
> [The implementation of this repository (textdistance without extras)](https://github.com/life4/textdistance/blob/33b67ae0d5286560a16fe3d9388a43016cdf3fc4/textdistance/algorithms/edit_based.py#L221-L319)
> 
> [The implementation of jellyfish](https://github.com/jamesturk/jellyfish/blob/713a432f0435ee2060923694df7904d0371f2c4a/jellyfish/_jellyfish.py#L43-L110)
> 
> [The implementation of python-Levenshtein](https://github.com/ztane/python-Levenshtein/blob/811c050ab71593879804a61347352764837d000f/Levenshtein/_levenshtein.c#L2811-L2843)

After playing this game (thanks for looking up the components!) I see that the `python-Levenshtein` [implementation](https://github.com/ztane/python-Levenshtein/blob/811c050ab71593879804a61347352764837d000f/Levenshtein/_levenshtein.c#L2837) does not limit the length of the prefix to a maximum of four characters. 

This repository, `jellyfish` and the [Wikipedia article for Jaro-Winkler](https://en.wikipedia.org/wiki/Jaro–Winkler_distance) do implement this maximum. There also remains an [unresolved issue](https://github.com/ztane/python-Levenshtein/issues/38) raised for this in the `python-Levenshtein` repo.

Considering the dismissive response to [a related issue](https://github.com/ztane/python-Levenshtein/issues/11) with the `python-Levenshtein` implementation, I would recommend removing this implementation from `textdistance` until it is corrected.

**Comment by orsinium** [comment]
Thank you for your research :+1:
