### ISSUE TITLE
LCS: behavior depends on parameter order

### ISSUE THREAD

**Issue by remidomingues** [life4/textdistance#40]
Hello team,

In most use cases, the following is True:
```
textdistance.lcsstr(s1, s2) == textdistance.lcsstr(s2, s1)
```
However, using a very long sequence (more than a few hundred characters) in second parameter breaks the current code, and we obtain an empty string as LCS.
```
In: textdistance.lcsstr('TEST', 'MYTEST'*100)
Out: ''
In: textdistance.lcsstr('MYTEST'*100, 'TEST')
Out: 'TEST'
```
Checking string length before sending them to difflib should probably be sufficient to patch this.

**Comment by orsinium** [comment]
Interesting. It breaks exactly on 200 characters long string. 199 is ok, 200 is empty :thinking:

**Comment by orsinium** [comment]
Caught it! Standard lib has optimization for long sequences:

```
if self.autojunk and n >= 200:
  ...
```
