### ISSUE TITLE
Is there a way to compare a string with another string that may have homoglyphs or visually similar characters in it

### ISSUE THREAD

**Issue by DavidRBailey** [life4/textdistance#47]
Is there a way, using this library, to compare a string with another string that may have homoglyphs or visually similar characters in it.

"quotes" ~= “quotes” : same (similar characters)
MacBride ~= McBride : different (obviously)
McBride ~= McBr𝗂de . : same (unicode homoglyph swap)

If not, then consider this a feature request. :-)

**Comment by orsinium** [comment]
Sure, use [homoglyphs](https://github.com/life4/homoglyphs):

```python
hg = homoglyphs.Homoglyphs()
hg.to_ascii('quotes') == hg.to_ascii('quotes')
# True
```
