### ISSUE TITLE
Question about Needleman-Wunsch

### ISSUE THREAD

**Issue by vadimkantorov** [life4/textdistance#61]
https://github.com/life4/textdistance/blob/f0e5e1254a3edc5f6e8066002ed3deb6586bf21f/textdistance/algorithms/edit_based.py#L402

Should it not instead read the following?
```python
match = dist_mat[i - 1, j - 1] + self.sim_func(s1[i], s2[j])
```
as is in https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm#Advanced_presentation_of_algorithm

Thanks!

**Comment by orsinium** [comment]
i and j start from 1 but strings are indexed from 0. I'll make it more clear.
